// fun/compliment.js
const compliments = [
  "You're amazing just the way you are.",
  "Your smile lights up the room.",
  "You have a great sense of humor!",
  "You're one of a kind.",
  "You make the world a better place.",
  "You bring so much positivity wherever you go.",
  "You have a beautiful soul.",
  "Your kindness is contagious.",
  "You're incredibly intelligent.",
  "You are a wonderful friend.",
  "You have a heart of gold.",
  "You make people feel at ease.",
  "You’re a true ray of sunshine.",
  "You're so talented and creative.",
  "You inspire those around you.",
  "You're a joy to be around.",
  "Your energy is unmatched.",
  "You're full of potential and drive.",
  "You're stronger than you think.",
  "You're doing great, keep it up!",
  "You have a unique perspective.",
  "Your laughter is infectious.",
  "You're always there when people need you.",
  "Your creativity knows no bounds.",
  "You're a natural leader.",
  "Your courage is inspiring.",
  "You're a great listener.",
  "You're incredibly hardworking.",
  "Your optimism is refreshing.",
  "You're such a good person.",
  "Your presence brightens everyone's day.",
  "You're such a great team player.",
  "You make everything you do seem effortless.",
  "You're always ready to help others.",
  "Your inner strength is impressive.",
  "You make people feel valued.",
  "Your attention to detail is amazing.",
  "You're so easy to talk to.",
  "You're a true original.",
  "You have an incredible work ethic.",
  "Your passion is evident in everything you do.",
  "You're a constant source of inspiration.",
  "You have a great sense of style.",
  "You’re so thoughtful.",
  "You're the kind of person people look up to.",
  "You're always thinking of others.",
  "You have an amazing ability to stay calm under pressure.",
  "You're someone people can always rely on.",
  "You're incredibly adaptable.",
  "Your sense of humor makes everything better.",
  "You're a true problem solver.",
  "You have such a kind heart.",
  "You're so considerate of other people's feelings.",
  "Your generosity knows no limits.",
  "You know how to make people feel special.",
  "You're always in the right place at the right time.",
  "Your advice is always so insightful.",
  "You're very dependable.",
  "You have a way of making people feel understood.",
  "You're a breath of fresh air.",
  "You’re incredibly resourceful.",
  "Your positive attitude makes the world a better place.",
  "You're so courageous, even in tough times.",
  "Your leadership is always appreciated.",
  "You make the impossible seem possible.",
  "You're full of wisdom.",
  "Your hard work never goes unnoticed.",
  "You're a great role model.",
  "You have a calming presence.",
  "You're always so thoughtful in your actions.",
  "You're always striving for improvement.",
  "You radiate warmth and kindness.",
  "You're so wise beyond your years.",
  "You're an amazing problem solver.",
  "You’re incredibly driven.",
  "You're such a kind and gentle soul.",
  "You light up every room you enter.",
  "You're a great mentor.",
  "You're one of the most empathetic people I know.",
  "You're always eager to learn and grow.",
  "You have a heart full of generosity.",
  "You're someone people can trust with anything.",
  "You're so graceful in everything you do.",
  "Your perspective is always so valuable.",
  "You're a great communicator.",
  "You have an infectious energy.",
  "You're such a positive force in the world.",
  "You're an absolute gem.",
  "You have a beautiful way with words.",
  "You're incredibly talented and skilled.",
  "You're so humble and down to earth.",
  "You're always pushing yourself to be better.",
  "You're a perfect example of kindness in action.",
  "You're so compassionate and understanding.",
  "You have an amazing ability to bring people together.",
  "You're so good at what you do.",
  "You're an extraordinary person.",
  "You always find the silver lining.",
  "You make people feel comfortable and safe.",
  "You're such an inspiring individual.",
  "You're always striving to make the world a better place.",
  "You're very intelligent and perceptive.",
  "You make such a positive impact on the world.",
  "You are so giving and selfless.",
  "You have such a calming effect on others.",
  "You're a true friend.",
  "You're a wonderful listener.",
  "You're a source of motivation for so many people.",
  "You're very kind-hearted.",
  "You bring out the best in others.",
  "You're always optimistic, even in tough times.",
  "You know how to brighten anyone’s day.",
  "You're so easy to love and be around.",
  "You're a wonderful person inside and out."
];

module.exports = compliments;
