// fun/dare.js
const dares = [
  "I dare you to sing your favorite song loudly in public.",
  "I dare you to call someone and tell them you love them.",
  "I dare you to do 20 push-ups in a row.",
  "I dare you to post an embarrassing photo of yourself on social media.",
  "I dare you to walk around your neighborhood in pajamas.",
  "I dare you to tell a joke to a stranger.",
  "I dare you to eat a spoonful of hot sauce.",
  "I dare you to dance in front of a mirror for 5 minutes.",
  "I dare you to wear socks on your hands for the next hour.",
  "I dare you to text your crush and say something silly.",
  "I dare you to wear a funny costume for the day.",
  "I dare you to try a new food you’ve never tasted before.",
  "I dare you to run around the block three times.",
  "I dare you to tell your funniest joke to a group of people.",
  "I dare you to say something nice to a stranger today.",
  "I dare you to write a heartfelt letter to someone.",
  "I dare you to hug a tree for 2 minutes.",
  "I dare you to give someone a compliment.",
  "I dare you to do your best impression of someone famous.",
  "I dare you to jump in place 20 times.",
  "I dare you to walk backwards for 5 minutes.",
  "I dare you to take a silly selfie and send it to a friend.",
  "I dare you to compliment a random person in the street.",
  "I dare you to imitate a baby for 2 minutes.",
  "I dare you to do 30 jumping jacks.",
  "I dare you to tell a funny story to someone.",
  "I dare you to wear your clothes inside out for an hour.",
  "I dare you to sing everything you say for the next 10 minutes.",
  "I dare you to eat a whole lemon without making a face.",
  "I dare you to walk around with a book on your head for 10 minutes.",
  "I dare you to call someone and sing happy birthday to them, even if it’s not their birthday.",
  "I dare you to speak in a different accent for the next 15 minutes.",
  "I dare you to hold a plank position for 2 minutes.",
  "I dare you to pretend to be a waiter/waitress for 5 minutes.",
  "I dare you to wear mismatched socks for the next day.",
  "I dare you to create a funny dance routine and perform it for someone.",
  "I dare you to write a poem about someone you admire.",
  "I dare you to do 20 sit-ups.",
  "I dare you to act like a celebrity for 10 minutes.",
  "I dare you to pretend you’re a famous singer and perform a song.",
  "I dare you to eat a raw onion slice.",
  "I dare you to try to balance on one foot for 1 minute.",
  "I dare you to give a speech about something random.",
  "I dare you to do an impression of your favorite cartoon character.",
  "I dare you to wear your shoes on the wrong feet for an hour.",
  "I dare you to draw a funny picture and show it to someone.",
  "I dare you to let someone else pick your outfit for the day.",
  "I dare you to walk like a zombie for 5 minutes.",
  "I dare you to talk in rhyme for the next 10 minutes.",
  "I dare you to eat a whole banana in one bite.",
  "I dare you to jump into a pool with all your clothes on.",
  "I dare you to take a walk while holding a spoon in your mouth.",
  "I dare you to send a meme to a friend without any explanation.",
  "I dare you to pretend to be a statue for 5 minutes.",
  "I dare you to walk up and down the stairs singing a song.",
  "I dare you to try to lick your elbow.",
  "I dare you to make a funny face and hold it for 30 seconds.",
  "I dare you to imitate a chicken for 1 minute.",
  "I dare you to say something nice to yourself in front of a mirror.",
  "I dare you to make a sandwich using only three ingredients.",
  "I dare you to give someone a 10-second hug.",
  "I dare you to create a new handshake with someone.",
  "I dare you to share a funny joke with a stranger.",
  "I dare you to do 15 squats.",
  "I dare you to stand on one leg for 2 minutes.",
  "I dare you to write a funny tweet and send it out.",
  "I dare you to text your mom and tell her you love her.",
  "I dare you to run in place for 3 minutes.",
  "I dare you to go for a walk with a big smile on your face.",
  "I dare you to do an impression of a robot.",
  "I dare you to speak in a funny voice for the next 10 minutes.",
  "I dare you to record a funny video and post it online.",
  "I dare you to try and touch your toes without bending your knees.",
  "I dare you to make up a song about a random topic.",
  "I dare you to hold your breath for 30 seconds.",
  "I dare you to send a funny meme to all your friends.",
  "I dare you to make animal noises for the next 2 minutes.",
  "I dare you to balance a spoon on your nose for 1 minute.",
  "I dare you to take a silly selfie and post it.",
  "I dare you to do 10 push-ups with your knees on the ground.",
  "I dare you to do an impression of your favorite celebrity.",
  "I dare you to eat a whole pickle in one bite.",
  "I dare you to try to make someone laugh by telling a joke.",
  "I dare you to wear a funny hat for the next 2 hours.",
  "I dare you to speak only in questions for the next 10 minutes.",
  "I dare you to take a 5-minute break and dance around.",
  "I dare you to tell a corny joke.",
  "I dare you to try to juggle three random objects.",
  "I dare you to text your best friend and tell them something embarrassing.",
  "I dare you to speak only in movie quotes for the next 10 minutes.",
  "I dare you to pretend you're a superhero for the next 10 minutes.",
  "I dare you to wear a funny face mask for an hour.",
  "I dare you to do a cartwheel.",
  "I dare you to find a friend and give them a high-five.",
  "I dare you to create a funny dance and perform it in public.",
  "I dare you to pretend to be a waiter and serve someone dinner.",
  "I dare you to try and sing a song without opening your mouth.",
  "I dare you to do 50 jumping jacks.",
  "I dare you to text a random friend and ask them how their day is going.",
  "I dare you to tell someone a funny story.",
  "I dare you to walk around your house like a crab for 5 minutes.",
  "I dare you to tell a joke to a family member.",
  "I dare you to make a TikTok video of something funny."
];

module.exports = dares;
