// fun/fact.js
const facts = [
  "Honey never spoils.",
  "A single cloud can weigh more than 1 million pounds.",
  "Bananas are berries, but strawberries aren't.",
  "An octopus has three hearts.",
  "You can't hum while holding your nose.",
  "Humans share 60% of their DNA with bananas.",
  "The Eiffel Tower can be 15 cm taller during the summer.",
  "Bees can recognize human faces.",
  "A group of flamingos is called a 'flamboyance.'",
  "A day on Venus is longer than a year on Venus.",
  "The longest hiccuping spree lasted 68 years.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
  "Sloths can hold their breath for up to 40 minutes underwater.",
  "You can't snore and dream at the same time.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "Sharks existed before trees.",
  "There are more stars in the universe than grains of sand on all of Earth's beaches.",
  "Wombat poop is cube-shaped.",
  "A snail can sleep for three years.",
  "The first alarm clock could only ring at 4 a.m.",
  "The longest time between two twins being born is 87 days.",
  "The shortest commercial flight in the world lasts only 57 seconds.",
  "More people are allergic to cow's milk than any other food.",
  "Cows have best friends.",
  "Cleopatra lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza.",
  "An apple a day keeps the doctor away... but it's mostly the fiber.",
  "The word 'bookkeeper' is the only unhyphenated English word with three consecutive double letters.",
  "The heart of a blue whale is the size of a small car.",
  "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis'.",
  "The world’s largest desert is not the Sahara, but Antarctica.",
  "Polar bear skin is black, although their fur is white.",
  "Honeybees can recognize human faces.",
  "A cockroach can live several weeks without its head.",
  "The Guinness World Record for the longest hiccuping spree is 68 years.",
  "A group of owls is called a parliament.",
  "The shortest commercial flight in the world is between two Scottish islands and lasts just 57 seconds.",
  "The longest time anyone has survived without water is 18 days.",
  "The Earth is not a perfect sphere; it is an oblate spheroid.",
  "There are more than 7,000 languages spoken in the world.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "There are more fake flamingos in the world than real ones.",
  "Butterflies taste with their feet.",
  "The smallest bone in the human body is the stapes bone in the ear.",
  "A newborn kangaroo is the size of a lima bean.",
  "The Eiffel Tower grows by 6 inches in the summer due to expansion from heat.",
  "The human nose can detect over 1 trillion different scents.",
  "In Japan, there is a museum dedicated to rocks that look like faces.",
  "There is enough DNA in the human body to stretch from the Sun to Pluto and back – 17 times.",
  "The longest wedding veil was longer than 63 football fields.",
  "A group of crows is called a murder.",
  "Octopuses have three hearts, blue blood, and the ability to regrow limbs.",
  "A crocodile cannot stick its tongue out.",
  "More people are allergic to cow's milk than any other food.",
  "A day on Venus is longer than a year on Venus.",
  "The shortest commercial flight in the world lasts 57 seconds.",
  "Cows have best friends and get stressed when separated.",
  "Cleopatra lived closer to the first Moon landing than to the construction of the Great Pyramid of Giza.",
  "Sharks existed before trees.",
  "Wombat poop is cube-shaped.",
  "Snails can sleep for up to three years.",
  "The longest hiccuping spree lasted 68 years.",
  "Sloths can hold their breath for up to 40 minutes underwater.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The Eiffel Tower can be 15 cm taller during the summer.",
  "A cockroach can live for weeks without its head.",
  "Bananas are berries, but strawberries aren't.",
  "There are more stars in the universe than grains of sand on all of Earth's beaches.",
  "The first alarm clock could only ring at 4 a.m.",
  "The longest time between two twins being born is 87 days.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
  "There is enough DNA in the human body to stretch from the Sun to Pluto and back – 17 times.",
  "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis'.",
  "Humans share 60% of their DNA with bananas.",
  "Polar bear skin is black, although their fur is white.",
  "Honey never spoils.",
  "Bees can recognize human faces.",
  "The heart of a blue whale is the size of a small car.",
  "A group of flamingos is called a 'flamboyance.'",
  "The longest hiccuping spree lasted 68 years.",
  "An octopus has three hearts.",
  "The Eiffel Tower can be 15 cm taller during the summer.",
  "The shortest commercial flight in the world lasts 57 seconds.",
  "Sloths can hold their breath for up to 40 minutes underwater.",
  "You can't snore and dream at the same time.",
  "Sharks existed before trees.",
  "There are more stars in the universe than grains of sand on all of Earth's beaches.",
  "Wombat poop is cube-shaped.",
  "A snail can sleep for three years.",
  "The first alarm clock could only ring at 4 a.m.",
  "The longest time between two twins being born is 87 days.",
  "The shortest commercial flight in the world lasts only 57 seconds."
];

module.exports = facts;
