// fun/joke.js
const jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don’t work out.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call an alligator in a vest? An investigator!",
    "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.",
    "What did the zero say to the eight? Nice belt!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "How does a penguin build its house? Igloos it together!",
    "Why don’t oysters share their pearls? Because they’re shellfish.",
    "Why was the math teacher suspicious? Because she had too many problems.",
    "What do you call a pile of cats? A meow-tain.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don’t skeletons ever use cell phones? They don’t have the fingers for it.",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why are ghosts bad at lying? Because they are too transparent.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why can’t you hear a pterodactyl go to the bathroom? Because the “P” is silent.",
    "What’s brown and sticky? A stick.",
    "What do you call a fish with no eyes? Fsh.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What did one wall say to the other wall? I’ll meet you at the corner.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don’t ants get sick? Because they have tiny ant-bodies.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "Why don’t you ever see elephants hiding in trees? Because they’re really, really good at it.",
    "What’s green and sings? Elvis Parsley.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "Why don’t they play poker in the jungle? Too many cheetahs.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why was the computer cold? Because it left its Windows open.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What did one hat say to the other hat? Stay here, I’m going on ahead!",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "Why was the computer so good at music? It had good byte.",
    "Why don’t fish play basketball? They’re afraid of the net.",
    "How do you organize a space party? You planet.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the broom get a promotion? Because it was always sweeping up!",
    "What do you call a man who lost all of his intelligence? A vegetable.",
    "Why did the cow go to space? To visit the Milky Way.",
    "What do you call a group of musical whales? An orca-stra.",
    "What do you call a dog magician? A labracadabrador."
  ];
  
  module.exports = jokes;
  