const pickuplines = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you French? Because Eiffel for you.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a parking ticket? Because you’ve got ‘fine’ written all over you.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Is your dad a boxer? Because you’re a knockout.",
    "Are you a campfire? Because you’re hot and I want s’more.",
    "Do you have a sunburn, or are you always this hot?",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Are you a 45-degree angle? Because you're acute-y.",
    "Is your name Chapstick? Because you're da balm.",
    "Are you a bank loan? Because you have my interest.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Is your dad a terrorist? Because you’re the bomb!",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Ariel? Because we’re mermaid for each other.",
    "Are you a time traveler? Because I see you in my future.",
    "Are you a snowstorm? Because you're making my heart race.",
    "Is it hot in here or is it just you?",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "Are you from Tennessee? Because you're the only 10 I see.",
    "Is your name Starbucks? Because I like you a latte.",
    "Are you a campfire? Because you’re smoking hot.",
    "If you were a fruit, you’d be a fine apple.",
    "Are you a pancake? Because you're flipping awesome.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a vampire? Because my heart beats faster when I'm around you."
  ];
  
  module.exports = pickuplines;  