// fun/quote.js
const quotes = [
  "Sometimes, the people you can't live without are the ones you can live best without.",
  "It’s hard to forget someone who gave you so much to remember.",
  "The saddest thing about betrayal is that it never comes from your enemies.",
  "The worst kind of pain is when you're smiling to stop the tears from falling.",
  "You never know how strong you are until being strong is your only choice.",
  "Sometimes you just have to accept that things won’t turn out the way you wanted.",
  "The only thing harder than letting go is moving on.",
  "I wish I could turn back time to tell you how much I cared before it was too late.",
  "It’s sad when you realize that not everyone you care about will stay in your life forever.",
  "The hardest part of letting go is realizing that you weren’t meant to hold on.",
  "It’s not the goodbye that hurts, but the flashbacks that follow.",
  "The most painful goodbyes are the ones that are never said, but the hearts already know.",
  "I hate that I still care about you, but I don’t know how to stop.",
  "Some days feel like the sadness will swallow you whole, and there's nothing left to do but wait.",
  "The worst feeling is not being lonely, but being forgotten by the person you thought would never forget you.",
  "Sometimes, you have to give up on people. Not because you don’t care, but because they don’t.",
  "You can’t change the past, but it can haunt you forever.",
  "You can’t always control who walks into your life, but you can control which pain stays in your heart.",
  "Sometimes it’s better to be alone than to have someone who makes you feel alone.",
  "The hardest part of loving someone is watching them drift away from you.",
  "Loneliness is a part of being human. It reminds us that we are not complete by ourselves.",
  "Sometimes, the people who hurt you the most are the ones you love the most.",
  "You can’t always be strong. There are days when it’s okay to cry and feel broken.",
  "The hardest part about missing someone is not knowing whether they miss you back.",
  "You can’t force someone to care about you, no matter how much you want them to.",
  "It’s okay to not be okay sometimes. Everyone has their bad days.",
  "The most painful feeling is when you love someone, but they don’t love you back.",
  "Some people leave, but they never really leave your heart.",
  "You can never truly forget the person who meant everything to you.",
  "The hardest thing is letting go of someone you thought would never leave.",
  "Love is not supposed to hurt, but sometimes it does.",
  "It’s hard to hold on when your heart is breaking.",
  "You think you’ve moved on, but something always pulls you back.",
  "No matter how much you care, some people will never care about you the same way.",
  "There are scars that you can’t see but they hurt the most.",
  "Sometimes, you need to step away from everything and just breathe.",
  "It’s hard to let go of someone who once meant the world to you.",
  "The worst kind of pain is when someone you love becomes a memory.",
  "Sometimes, the one person you want to be with is the one you can’t have.",
  "The emptiness in your heart can only be filled by someone who truly cares.",
  "The worst thing about moving on is that you can’t go back.",
  "Love doesn’t always mean happiness. Sometimes it means heartbreak and tears.",
  "The hardest part of life is watching the person you love drift away, no matter how hard you try.",
  "Time doesn’t heal everything. Some wounds stay forever.",
  "Sometimes, you just need a hug to make the pain feel a little less real.",
  "The pain of losing someone is only bearable if you let yourself feel it.",
  "You can only be strong for so long before you need to let your guard down.",
  "Even the strongest people break down sometimes.",
  "The hardest part of being in love is when it’s unrequited.",
  "The most painful thing is seeing someone you love with someone else.",
  "The pain of the past can linger forever, no matter how much you try to move on.",
  "Loneliness isn’t just about being alone; it’s about feeling alone even when you’re with people.",
  "The hardest thing to do is forgive someone who hurt you deeply.",
  "It’s hard to say goodbye to someone who was never really yours.",
  "Time doesn’t heal all wounds. Some wounds stay fresh no matter how much time passes.",
  "Not all scars are visible, but that doesn’t mean they don’t hurt.",
  "It’s easier to pretend that everything’s okay than to admit that it’s not.",
  "Sometimes, the best thing you can do is walk away, even though you don’t want to.",
  "Sometimes the people who hurt you the most are the ones who never meant to.",
  "You can’t hold onto someone who doesn’t want to stay.",
  "It’s okay to miss someone, but it’s not okay to let them take over your life.",
  "The worst thing you can do is give someone all of your love when they don’t appreciate it.",
  "You may not realize it, but your absence can break someone’s heart.",
  "The emptiness that comes with losing someone is something no one can explain.",
  "Sometimes, the best thing to do is let go of the people who hold you back.",
  "The longer you wait for something, the more you realize you’re better off without it.",
  "The pain of losing someone never truly goes away, it just becomes easier to live with.",
  "When you feel like giving up, just remember that things can get better.",
  "Some people stay with you even when they leave. Their memories never truly fade.",
  "Sometimes, no matter how hard you try, things just don’t work out the way you want them to.",
  "Love is a beautiful thing until it turns into something painful.",
  "The most painful part about missing someone is that you can’t get them back.",
  "Not all wounds heal with time. Some remain open forever.",
  "Sometimes, you have to let go of the person you love, even if you still love them.",
  "The worst kind of sadness is not being able to tell someone you miss them.",
  "Sometimes the person you want the most is the one you can’t have.",
  "You can’t love someone back to life if they’re already gone.",
  "The emptiness left behind by someone you love is hard to fill.",
  "You’ll never forget the person who changed your life, no matter how much time passes.",
  "It’s difficult to move on when you still hope things will work out.",
  "Love may fade, but the memories of it last forever.",
  "Some people leave, but their memories stay etched in your heart forever.",
  "It’s hard to stop loving someone who never really cared.",
  "The best way to forget someone is to keep busy with someone who actually cares.",
  "Love isn’t always enough to keep someone in your life.",
  "The hardest part about love is knowing when to let go.",
  "Sometimes, it’s better to stay silent than to say something that could hurt.",
  "You can’t make someone love you, no matter how hard you try.",
  "Sometimes, saying goodbye is the only way to move on.",
  "The hardest part about losing someone is not having the chance to say goodbye.",
  "You can never be fully prepared for the pain of losing someone.",
  "When someone you love is no longer in your life, it’s hard to find a way to move forward.",
  "Sometimes, the memories are the only things that keep you going.",
  "The hardest part of loving someone is when they don’t love you back.",
  "The hardest goodbye is the one you never wanted to say."
];

module.exports = quotes;
