// fun/riddle.js
const riddles = [
  "What has keys but can’t open locks? A piano.",
  "What has a head, a tail, but no body? A coin.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter M.",
  "What can travel around the world while staying in the corner? A stamp.",
  "What has hands but can’t clap? A clock.",
  "What has a neck but no head? A bottle.",
  "What has legs but doesn’t walk? A table.",
  "I’m tall when I’m young, and I’m short when I’m old. What am I? A candle.",
  "What can you break but never touch? A promise.",
  "What’s full of holes but still holds a lot of weight? A net.",
  "What comes down but never goes up? Rain.",
  "What has one eye but can’t see? A needle.",
  "What gets wetter as it dries? A towel.",
  "What has a bed but never sleeps? A river.",
  "What has an end but no beginning? A stick.",
  "What is always in front of you but can’t be seen? The future.",
  "What can you catch but not throw? A cold.",
  "What’s black and white and read all over? A newspaper.",
  "What has a heart that doesn’t beat? An artichoke.",
  "What runs but never walks? Water.",
  "What can’t be used until it’s broken? An egg.",
  "What has a foot but no legs? A ruler.",
  "What has cities, but no houses? A map.",
  "What has ears but can’t hear? A cornfield.",
  "What can you hold in your left hand but not in your right? Your right elbow.",
  "What’s light as a feather, yet the strongest man can’t hold it for much longer? Your breath.",
  "What has a face but no eyes? A clock.",
  "What gets bigger the more you take away? A hole.",
  "What’s easy to get into but hard to get out of? Trouble.",
  "What starts with an E, ends with an E, but only has one letter? An envelope.",
  "What has a tail but no body? A coin.",
  "What has four fingers but isn’t alive? A glove.",
  "What’s the longest word in the dictionary? Smiles, because there’s a mile between the first and last letters.",
  "What’s always coming but never arrives? Tomorrow.",
  "What’s black and white and red all over? A sunburned zebra.",
  "What has 88 keys but can’t open a single door? A piano.",
  "What kind of coat can only be put on when wet? A coat of paint.",
  "What has a thumb and four fingers but isn’t alive? A glove.",
  "What has a bottom at the top? A leg.",
  "What’s a big word but small in size? A small letter.",
  "What goes up but never comes down? Your age.",
  "What can be cracked, made, told, and played? A joke.",
  "What is always in front of you but can’t be seen? The future.",
  "What can be heard but not seen? Sound.",
  "What starts with a P, ends with an E, and has thousands of letters? The post office.",
  "What has 13 hearts but no other organs? A deck of playing cards.",
  "What’s black and white and goes around and around? A penguin in a revolving door.",
  "What’s as light as a feather, but the strongest man can’t hold it for much longer? His breath.",
  "What belongs to you, but others use it more than you do? Your name.",
  "What can be cracked but not touched? A promise.",
  "What is always with you but never seen? Your shadow.",
  "What has words but never speaks? A book.",
  "What gets sharper the more you use it? Your mind.",
  "What starts with a T, ends with a T, and has T in it? A teapot.",
  "What is so fragile that saying its name breaks it? Silence.",
  "What goes up and down but doesn’t move? A staircase.",
  "What has no beginning, no end, and no middle? A doughnut.",
  "What has a bark but no bite? A tree.",
  "What can’t be seen but can make you feel cold? The wind.",
  "What has no life but can grow? A rock.",
  "What happens once in a year, twice in a week, but never in a day? The letter E.",
  "What gets bigger the more you take away from it? A hole.",
  "What is full of holes but still holds water? A sponge.",
  "What word is spelled incorrectly in every dictionary? Incorrectly.",
  "What is something that goes up and never comes down? Your age.",
  "What gets wetter the more it dries? A towel.",
  "What is so delicate that even mentioning it can break it? Silence.",
  "What has keys but can’t open locks? A piano.",
  "What can travel around the world but stays in a corner? A stamp.",
  "What has a lot of teeth but can’t bite? A comb.",
  "What can you hold without ever touching it? A conversation.",
  "What has legs but can’t walk? A table.",
  "What can’t you keep but can spend? Time.",
  "What goes up but never comes down? Your age.",
  "What has an eye but can’t see? A needle.",
  "What’s always on the ground but never gets dirty? A shadow.",
  "What is invisible but makes things visible? Light.",
  "What runs but never walks? Water.",
  "What has a neck but no head? A bottle.",
  "What can’t be touched but can be felt? The wind.",
  "What comes once in a year, twice in a month, but never in a day? The letter E.",
  "What has a head, a tail, but no body? A coin.",
  "What’s at the end of a rainbow? The letter W.",
  "What comes down but never goes up? Rain.",
  "What can be cracked, made, told, and played? A joke.",
  "What has a lot of keys but can’t open a lock? A piano.",
  "What can be heard but not seen? Sound.",
  "What’s full of holes but still holds water? A sponge.",
  "What has a bottom at the top? A leg.",
  "What’s full of holes but still holds weight? A net.",
  "What’s invisible but always present? Air.",
  "What has a head and a tail but no body? A coin.",
  "What runs but never walks? A river.",
  "What starts with a P, ends with an E, and has a thousand letters in it? A post office.",
  "What goes up but never comes down? Your age.",
  "What has a face but no eyes? A clock.",
  "What is so fragile that saying its name breaks it? Silence."
];

module.exports = riddles;
