// fun/truth.js
const truths = [
  "Have you ever lied to get out of trouble?",
  "What’s the most embarrassing thing you’ve ever done?",
  "What’s a secret you’ve never told anyone?",
  "Have you ever cheated in a relationship?",
  "If you could swap lives with someone for a day, who would it be?",
  "What’s the most childish thing you still do?",
  "Have you ever stolen something?",
  "What’s the worst thing you’ve ever done to someone?",
  "What’s the biggest lie you’ve ever told?",
  "What’s something you’ve never told your parents?",
  "Have you ever said I love you but didn’t mean it?",
  "What’s the most embarrassing thing that’s happened to you in school?",
  "What’s something you’re afraid to do but wish you could?",
  "What’s the worst advice you’ve ever received?",
  "Have you ever been in love with someone who didn’t feel the same way?",
  "What’s something you’ve always wanted to try but haven’t?",
  "What’s the biggest regret you have in life?",
  "Have you ever been in a physical fight?",
  "What’s the most awkward situation you’ve ever been in?",
  "If you could change one thing about your life, what would it be?",
  "What’s something you’ve done that you’re proud of?",
  "What’s your biggest fear?",
  "What’s a habit you wish you could break?",
  "What’s the most hurtful thing someone’s ever said to you?",
  "What’s the most embarrassing thing you’ve ever worn?",
  "What’s a decision you made that you regret?",
  "Have you ever been caught doing something you weren’t supposed to?",
  "What’s a talent you have that no one knows about?",
  "What’s the worst mistake you’ve ever made?",
  "What’s something you’ve always wanted to change about yourself?",
  "What’s the most embarrassing thing you’ve said to someone you like?",
  "Have you ever been in trouble with the law?",
  "What’s the most embarrassing thing that’s happened to you on a date?",
  "What’s the longest you’ve gone without telling someone the truth?",
  "What’s something you’ve done that you’re ashamed of?",
  "Have you ever had a crush on someone who didn’t know you existed?",
  "What’s the worst gift you’ve ever received?",
  "What’s something you’ve done that no one knows about?",
  "What’s something that makes you feel insecure?",
  "What’s something you’ve done to get someone’s attention?",
  "What’s the biggest lie you’ve ever heard someone tell?",
  "What’s something you’ve done that you would never do again?",
  "Have you ever been caught cheating?",
  "What’s the most embarrassing thing that’s happened to you at work?",
  "What’s the most outrageous thing you’ve ever done for money?",
  "What’s the most reckless thing you’ve ever done?",
  "What’s something you’ve done to impress someone?",
  "What’s the most embarrassing moment you’ve had with a friend?",
  "Have you ever been rejected by someone you liked?",
  "What’s the most dramatic thing that’s happened to you?",
  "What’s something you wish you could say to someone but haven’t?",
  "What’s the most awkward thing you’ve done to impress someone?",
  "What’s something that makes you feel anxious?",
  "What’s the most childish thing you’ve done in public?",
  "Have you ever lied to someone to make them feel better?",
  "What’s the most embarrassing thing you’ve ever done at a family gathering?",
  "What’s something you’ve done that you thought was a good idea but wasn’t?",
  "What’s the most awkward situation you’ve had with a family member?",
  "What’s something you’re embarrassed to admit you enjoy?",
  "What’s something you would never want anyone to find out about you?",
  "What’s a lie you’ve told that’s come back to haunt you?",
  "Have you ever been in a love triangle?",
  "What’s something that makes you feel judged?",
  "What’s the most embarrassing text you’ve ever sent?",
  "What’s something you’ve done to get revenge on someone?",
  "What’s the most embarrassing thing you’ve done in front of your parents?",
  "What’s the most embarrassing thing you’ve done in front of your friends?",
  "What’s something you’ve done out of anger that you regret?",
  "What’s the worst decision you’ve ever made in a relationship?",
  "What’s the most embarrassing thing you’ve done at a party?",
  "Have you ever gotten in trouble for something you didn’t do?",
  "What’s the worst thing you’ve ever said to someone you care about?",
  "What’s the most embarrassing thing you’ve done in front of a crush?",
  "What’s something you’ve done to avoid confrontation?",
  "What’s the worst advice you’ve given someone?",
  "What’s the most awkward thing you’ve done while trying to make a good impression?",
  "What’s something you’ve done for attention that you regret?",
  "Have you ever broken someone’s heart?",
  "What’s the most awkward thing you’ve done while trying to be funny?",
  "What’s something you’ve done that you never thought you would?",
  "What’s the most embarrassing thing that’s happened to you in front of a teacher?",
  "What’s something that still makes you feel embarrassed even though it happened a long time ago?",
  "What’s the most embarrassing thing that’s happened to you in a public place?",
  "Have you ever tried to change someone just to make them like you?",
  "What’s the most embarrassing thing you’ve said to a teacher?",
  "What’s something you wish you could go back and do differently?",
  "Have you ever been lied to by someone close to you?",
  "What’s the most embarrassing thing that’s happened to you while traveling?",
  "What’s something that you did as a child that you still remember?",
  "What’s something you’ve been too afraid to admit to anyone?",
  "What’s the worst thing you’ve ever done for attention?",
  "What’s the most awkward thing you’ve done in a social setting?",
  "Have you ever ghosted someone?",
  "What’s the most embarrassing thing that’s happened to you at work?",
  "What’s something that you thought was a good idea but turned out terribly?",
  "What’s something you regret doing because you were trying to impress someone?"
];

module.exports = truths;
