const wouldYourather = [
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather fight 100 duck-sized horses or one horse-sized duck?",
    "Would you rather always have to sing instead of speak or dance everywhere you go?",
    "Would you rather live without music or live without TV?",
    "Would you rather have fingers for toes or toes for fingers?",
    "Would you rather be able to talk to animals or speak every human language?",
    "Would you rather eat pizza every day or never eat pizza again?",
    "Would you rather have a time machine or a teleportation device?",
    "Would you rather be able to breathe underwater or fly through the air?",
    "Would you rather win the lottery or find your true love?",
    "Would you rather never be able to use social media again or never be able to watch movies again?",
    "Would you rather have free Wi-Fi wherever you go or have free coffee wherever you go?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather have the ability to see the future or change the past?",
    "Would you rather always have to sing in the shower or always dance while cooking?",
    "Would you rather have a pet dinosaur or a pet dragon?",
    "Would you rather live in a world where everyone tells the truth or everyone lies?",
    "Would you rather be able to visit space or explore the deep ocean?",
    "Would you rather be famous for a day or rich for a day?",
    "Would you rather travel to a new country every year or stay in one country for the rest of your life?",
    "Would you rather never have to sleep or never have to eat?",
    "Would you rather have the power to heal others or the power to teleport?",
    "Would you rather be able to time travel or teleport?",
    "Would you rather have a photographic memory or be able to forget anything you want?",
    "Would you rather always have to wear a superhero costume or always wear pajamas?",
    "Would you rather have the ability to read minds or control minds?",
    "Would you rather live on a beach or in the mountains?",
    "Would you rather always have to tell the truth or always have to lie?",
    "Would you rather live in a mansion or in a cozy cottage?",
    "Would you rather have an endless supply of chocolate or an endless supply of coffee?"
  ];
  
  module.exports = wouldYourather;
  